default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  timeout: 5000 # Timeout in milliseconds for connections
  
  # Optional settings to enhance connection stability and performance
  # You can uncomment and adjust the following as needed:
  # host: localhost
  # port: 5432

development:
  <<: *default
  database: cvtheque_api_development
  username: "user"
  password: "cvtheque@@u5"
  # Optional: Adjust the host and port if needed
  # host: localhost
  # port: 5432

test:
  <<: *default
  database: test_cvtheque_api
  username: "user"
  password: "cvtheque@@u5"
  # Optional: Adjust the host and port if needed
  # host: localhost
  # port: 5432

production:
  <<: *default
  database: cvtheque_api_production
  username: "user"
  password: "<%= ENV['DATABASE_PASSWORD'] %>" # Use environment variable for password
  host: "<%= ENV['DATABASE_HOST'] %>" # Use environment variable for host
  port: <%= ENV['DATABASE_PORT'] || 5432 %> # Use environment variable for port, default to 5432
